@php use Carbon\Carbon; @endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Summary Report</title>
    <style>
        @page { margin: 40px 20px; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 9px; margin: 0; padding: 0; color: #000; }

        .page-header {
            position: fixed;
            top: -30px;
            left: 0;
            right: 0;
            height: 35px;
            text-align: center;
        }

        .header-title {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .header-subtitle {
            font-size: 9px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #000;
            padding: 6px 4px;
            text-align: center;
        }

        th {
            background-color: #FADAD3;
            font-weight: bold;
            font-size: 9px;
        }

        td {
            font-size: 8px;
        }

        .row-odd {
            background-color: #FFF3E6;
        }

        .dept-col {
            text-align: left;
            padding-left: 8px;
        }

        .footer {
            position: fixed;
            bottom: -20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 8px;
            color: #777;
        }

        .summary-info {
            margin-bottom: 10px;
            font-size: 9px;
        }

        .summary-info strong {
            font-weight: bold;
        }
    </style>
</head>
<body>

<div class="page-header">
    <div class="header-title">Attendance Summary Report</div>
    <div class="header-subtitle">
        {{ $filters['start_date'] }}
        @if($filters['start_date'] !== $filters['end_date'])
            <span>to {{ $filters['end_date'] }}</span>
        @endif
    </div>
</div>

<div class="summary-info">
    <strong>Generated:</strong> {{ $generated_at }} |
    <strong>Total Records:</strong> {{ count($summary) }}
</div>

<table>
    <thead>
        <tr>
            <th style="width: 5%;">SR #</th>
            <th style="width: 12%;">Date</th>
            <th style="width: 10%;">Total</br>Employees</th>
            <th style="width: 8%;">Total</br>Present</th>
            <th style="width: 8%;">On Time</th>
            <th style="width: 5%;">Late</th>
            <th style="width: 8%;">Short</br>Leaves</th>
            <th style="width: 8%;">Half</br>Leaves</th>
            <th style="width: 8%;">Leaves</th>
            <th style="width: 8%;">Absent</th>
            <th style="width: 10%;">On-Time %</th>
        </tr>
    </thead>
    <tbody>
        @forelse($summary as $index => $row)
            <tr class="{{ $index % 2 === 1 ? 'row-odd' : '' }}">
                <td>{{ $index + 1 }}</td>
                <td>{{ Carbon::parse($row->date)->format('d-m-Y') }}</td>
                <td>{{ $row->total_employees }}</td>
                <td>{{ $row->present_or_late_count }}</td>
                <td>{{ $row->present_count }}</td>
                <td>{{ $row->late_count }}</td>
                <td>{{ $row->short_leaves }}</td>
                <td>{{ $row->half_leaves }}</td>
                <td>{{ $row->approved_leaves }}</td>
                <td>{{ $row->absent_count }}</td>
                <td>{{ $row->on_time_percentage ? number_format($row->on_time_percentage, 1) . '%' : '0.0%' }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="10" style="padding: 20px; text-align: center;">No data available for the selected period.</td>
            </tr>
        @endforelse
    </tbody>
</table>
<div class="footer">
    Page <span class="pagenum"></span> | Generated by ZAL ERP System
</div>
</body>
</html>

